name: thing-directory
base: core20 

# take the version from part
adopt-info: thing-directory

summary: A W3C WoT Thing Description Directory
description: |
  This is a lightweight implementation of a WoT Thing Description Directory,
  described by the [W3C Discovery](https://w3c.github.io/wot-discovery/) standard specification.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  thing-directory:
    command: bin/thing-directory -conf $SNAP/conf/thing-directory.json
    environment: 
      TD_VALIDATION_JSONSCHEMAS: "$SNAP/conf/wot_td_schema.json,$SNAP/conf/wot_discovery_schema.json"
    daemon: simple
    plugs: 
      - network-bind

parts:
  thing-directory:
    plugin: go
    source: .
    build-packages:
      - curl
      - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags)
    override-prime: |
      mkdir -p conf
      curl https://raw.githubusercontent.com/w3c/wot-thing-description/REC1.0/validation/td-json-schema-validation.json -o conf/wot_td_schema.json
      curl https://raw.githubusercontent.com/w3c/wot-discovery/main/validation/td-discovery-extensions-json-schema.json -o conf/wot_discovery_schema.json
      cp $SNAPCRAFT_PART_SRC/sample_conf/thing-directory.json conf/thing-directory.json
      snapcraftctl prime
